#!/bin/bash

BASE_PATH="$(cd "$( dirname "$0" )" &> /dev/null && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RED_BOLD='\033[1;31m'
GREEN_BOLD='\033[1;32m'
YELLOW_BOLD='\033[1;33m'
BLUE_BOLD='\033[1;34m'
RESET='\033[0m'

p() {
  echo -e "${RESET}${YELLOW_BOLD}$0${YELLOW}: $1${RESET}"
}

confirm() {
  read -p "Confirm to $1? [Y/n]: " value
  if [ "$value" == "Y" ] || [ "$value" == "y" ] || [ "$value" == "" ]; then
    $1
  else
    exit 0
  fi
}

packages() {
  yay -S --needed --asdeps $(cat $BASE_PATH/packages/deps.txt); yay -S --needed $(cat $BASE_PATH/packages/main.txt)
}

install() {
  if ! which yay &> /dev/null; then
    p "${RED_BOLD}yay (AUR Helper) ${RED}not found!!"
    p "${BLUE}Installing yay-bin..."
    git clone https://aur.archlinux.org/yay-bin.git ~/.cache/yay/yay-bin; cd ~/.cache/yay/yay-bin; makepkg -si
  fi

  p "${BLUE}Installing packages..."
  packages

  sudo systemctl enable --now nix-daemon

  p "${BLUE}Adding user \"$(whoami)\" to nixbld groups..."
  sudo gpasswd -a $(whoami) nixbld

  p "${BLUE}Updating nix-channels..."
  nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  nix-channel --update

  p "${BLUE}Adding nix.conf..."
  sudo rsync -av $BASE_PATH/etc/* /etc/
  nix profile add home-manager
  home-manager switch -b backup --flake .#leo

  p "${BLUE}Sync \"/home/$(whoami)/.local/share/*\"..."
  rsync -av $BASE_PATH/local/* ~/.local/

  p "${BLUE}Sync \"/home/$(whoami)/.config/*\"..."
  rsync -av $BASE_PATH/config/* ~/.config/

  p "${BLUE}Set papirus folder to yaru"
  papirus-folders -C yaru --theme Papirus-Dark

  p "${BLUE}Set gtk icon to papirus"
  gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
}

update() {
  p "${BLUE}Updating packages..."
  packages

  home-manager switch -b backup --flake .#leo

  p "${BLUE}Sync \"/home/$(whoami)/.local/share/*\"..."
  rsync -av $BASE_PATH/local/* ~/.local/

  p "${BLUE}Sync \"/home/$(whoami)/.config/*\"..."
  rsync -av $BASE_PATH/config/* ~/.config/
}

cleannix() {
  p "${BLUE}Cleaning nix store..."
  nix-collect-garbage -d
  home-manager switch -b backup --flake .#leo
}

uninstall() {
  p "Uninstalling..."
  sudo systemctl stop nix-daemon
  sudo systemctl disable nix-daemon
  sudo gpasswd -d $(whoami) nixbld
  for i in {01..10}; do
    sudo userdel "nixbld$i"
  done
  sudo groupdel nixbld
  sudo rm -rf /nix /etx/nix
  rm -rf $(cat $BASE_PATH/dirs/main.txt)
}

# test() {
#   p "test"
# }

case $1 in
  install|i)
    confirm install
    ;;
  update|u)
    confirm update
    ;;
  cleannix|cn)
    confirm cleannix
    ;;
  uninstall|ui)
    confirm uninstall
    ;;
  # test|t)
  #   confirm test
  #   ;;
  "")
    confirm install
    ;;
  *)
    p "${RED_BOLD}\"$1\" ${RED}is unknown option!!"
    exit 1
    ;;
esac
